name: Build Mihon PT-BR Hub

on:
  workflow_dispatch:
  push:
    paths:
      - 'Mihon_PTBR_Hub_COMPLETO/**'
      - '.github/workflows/build.yml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Baixar framework atual do Keiyoushi
        uses: actions/checkout@v4
        with:
          repository: keiyoushi/extensions-source
          path: upstream

      - name: Copiar nossa extensão para o framework
        run: |
          rm -rf upstream/src/pt/mihonptbrhub
          mkdir -p upstream/src/pt
          cp -R "Mihon_PTBR_Hub_COMPLETO/src/pt/mihonptbrhub" "upstream/src/pt/"

      - name: Compilar extensão
        working-directory: upstream
        run: ./gradlew :src:pt:mihonptbrhub:assembleRelease --stacktrace

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: mihon-ptbr-hub-apk
          path: upstream/src/pt/mihonptbrhub/build/outputs/apk/release/*.apk
          if-no-files-found: error
